## Variable

<br>

- 우리가 아는 그 변수.
- 보통 int a, char b 이런식으로 선언했지만, TensorFlow에선 tf.Variable()을 통해 선언해야 함.
- 기존 언어의 자료형과 마찬가지로 Bool-Type, Complex-Type을 가질 수 있음.

In [1]:
import tensorflow as tf

In [3]:
myTensor = tf.constant([[1.0, 2.0], [3.0, 4.0]]) # constant 선언
myVariable = tf.Variable(myTensor) # Variable 선언

print('변수의 형태 : ', myVariable.shape)
print('자료형 : ', myVariable.dtype)
print('넘파이로 변환? ', myVariable.numpy)

변수의 형태 :  (2, 2)
자료형 :  <dtype: 'float32'>
넘파이로 변환?  <bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>>


In [4]:
# 변수 재 구성은 할 수 없지만, 대부분의 텐서 연산도 변수에 대해 작동함.
print(myVariable)
print('\n텐서로 변환 : ', tf.convert_to_tensor(myVariable))
print('\n복사 후 reshaping : ', tf.reshape(myVariable, ([1,4]))) # 새 텐서를 만듬. 기존 텐서 변형 X.

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

텐서로 변환 :  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

복사 후 reshaping :  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


In [6]:
# assign 을 이용해 텐서를 재 할당 할 수 있음. 
# 새 텐서가 할당되는 것이 아님. 기존 텐서의 메모리가 재사용 됨.
a = tf.Variable([2.0, 3.0])
a.assign([1, 2]) # 2.0 3.0 --> 1.0 2.0 으로 재 할당 됨. 
print(a, '\n')

# 크기 변형은 안된다.
try:
    a.assign([1.0, 2.0, 3.0])
except Exception as e:
    print(f'{type(e).__name__} : {e}')

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)> 

ValueError : Shapes (2,) and (3,) are incompatible


In [8]:
a = tf.Variable([2.0, 3.0])
b = tf.Variable(a) # a 값을 기준으로 하는 새 변수 생성.
a.assign([5, 6]) # b 선언 후 a 값을 재할당?

# a만 바뀌었음. 흐름상으로 보면 당연한 이야기.
# 좀 더 고급스럽게 얘기하면, 두 변수는 같은 메모리 공간을 공유하지 않음.
# 먼저 선언된 a를 복제해서 b를 만든 것.
print(a.numpy())
print(b.numpy()) 

# 연산을 바로 적용시켜 할당할 수도 있음.
a.assign_add([2,3])
b.assign_add([7,9])
print(a.numpy())
print(b.numpy())

[5. 6.]
[2. 3.]
[7. 9.]
[ 9. 12.]


**수명주기**  <br>
- 일반적으로 Python 객체와 같은 수명주기를 가짐.
- 변수에 대한 참조가 없으면 자동으로 할당 해제.
- **변수에 이름을 지정**해 디버깅 하는데 도움을 받을 수도 있음. 
    - 이때 이름은 중복될 수도 있다.

In [9]:
a = tf.Variable(myTensor, name='Kim')
b = tf.Variable(myTensor+1, name='Kim')

print(a == b) # elementwise unequal 하므로 모두 False가 나옴.

tf.Tensor(
[[False False]
 [False False]], shape=(2, 2), dtype=bool)


**변수 및 텐서 배치**  <br>
- 텐서를 CPU, GPU에 배치해서 빠른 연산이 가능함.

In [12]:
with tf.device('CPU:0'):
    # 임의이 텐서 생성
    a = tf.Variable([[1,2,3], [4,5,6]])
    b = tf.constant([[1,2], [3,4], [5,6]])
    x = tf.Variable([[1,2,3], [4,5,6]])
    y = tf.Variable([[1,2,3]])
    c = tf.matmul(a, b)
print(c)  

# 연산할 변수를 다른 기기에 등록해 수행할 수도 있음.
with tf.device('GPU:0'):
    k = x * y
print(k)

tf.Tensor(
[[22 28]
 [49 64]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1  4  9]
 [ 4 10 18]], shape=(2, 3), dtype=int32)
