In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [6]:
a2 = np.array([[1,2,3,4], [11,12,13,14]])
a2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [7]:
a3 = np.array([[[1,2,3,4],[11,12,13,14]], [[21,22,23,24],[31,32,33,34]]])
a3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [9]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [11]:
z = np.zeros([4]) # 0으로 채운 배열
o = np.ones([3,4]) # 1로 채운 배열
r = np.random.randn(2,3) # 2*3 크기의 정규난수 배열 생성

In [12]:
z, o, r

(array([0., 0., 0., 0.]), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]), array([[ 0.3847274 , -0.60333533,  1.04625852],
        [ 0.39561722,  0.83088449, -1.4505872 ]]))

In [13]:
r4 = np.random.randn(2,2,4,5).round(3) # 임의의 4차원 배열 생성
r4

array([[[[ 0.357,  0.488, -0.985,  1.329,  1.424],
         [-0.306, -0.441,  1.1  , -0.211,  0.814],
         [ 0.294, -0.771,  0.153, -1.604,  0.155],
         [ 0.107,  1.048, -1.132, -1.931, -0.465]],

        [[ 0.252, -0.056,  1.52 ,  0.981,  0.757],
         [-0.824,  0.508, -0.426, -0.749,  0.041],
         [-0.313, -0.03 ,  1.093, -0.974,  0.703],
         [-0.673,  1.015, -0.738,  1.576, -0.536]]],


       [[[ 0.246,  0.319,  0.077, -0.26 ,  0.285],
         [-0.968, -1.463,  0.051, -0.824, -0.637],
         [ 0.135,  0.166,  0.631, -0.082,  0.709],
         [-0.355,  0.403, -0.961, -0.59 , -0.118]],

        [[ 2.303, -1.471, -0.866, -0.854,  1.577],
         [ 0.606,  0.701, -1.253, -0.097, -0.12 ],
         [ 1.038,  0.853,  1.914,  0.176, -0.611],
         [ 0.793, -0.441,  1.667,  0.358,  0.846]]]])

In [14]:
r4[1][0] # 2번째 큰 배열에서 첫번째 배열 선택

array([[ 0.246,  0.319,  0.077, -0.26 ,  0.285],
       [-0.968, -1.463,  0.051, -0.824, -0.637],
       [ 0.135,  0.166,  0.631, -0.082,  0.709],
       [-0.355,  0.403, -0.961, -0.59 , -0.118]])

In [15]:
r4[1][0][2] # 2번째 큰 배열에서 첫번째 배열 선택, 거기서 세번째 행 선택

array([ 0.135,  0.166,  0.631, -0.082,  0.709])

In [16]:
r4[1][0][2][4] # 2번째 큰 배열에서 첫번째 배열 선택, 세번째 행의 5번째 원소 선택

0.709

In [17]:
r4[1][0][0:4:2] # 2번째 큰 배열에서 첫번째 배열 선택, slicing써서 1,3번째 행 선택

array([[ 0.246,  0.319,  0.077, -0.26 ,  0.285],
       [ 0.135,  0.166,  0.631, -0.082,  0.709]])