## R List

<br>



- 리스트 : Vector와 동일한 형태이지만, Vector와는 다르게 **숫자, 문자 등 여러 형태가 섞임.** 이형적 데이터 구조.
    - **list(key1=value1, key2=value2, ...)** 로 선언.
    - 마찬가지로 index번호로 접근 가능.

In [2]:
a <- list('Kim', 'Coder', 'Seoul', 1.1)
a

[[1]]
[1] "Kim"

[[2]]
[1] "Coder"

[[3]]
[1] "Seoul"

[[4]]
[1] 1.1

In [3]:
myList <- list(friend = 'Park', num = 2, alpha = 'z') # 3개의 요소로 구성된 리스트.
myList # $key - value 형식으로 출력됨.

$friend
[1] "Park"

$num
[1] 2

$alpha
[1] "z"

In [5]:
# 여러 요소 중 특정 key의 value만 접근?
myList$friend
myList$num

[1] "Park"

[1] 2

**List에 항목 추가**

<br>

- **변수명$추가할key <- 값** 을 통해 추가 가능.
- 하나의 key에 여러 값을 넣어줄 수도 있음. Vector로.

In [7]:
myList$word <- 'hello'
myList

myList$food <- c('Pizza', 'Hotdog', 'Rice')
myList

$friend
[1] "Park"

$num
[1] 2

$alpha
[1] "z"

$word
[1] "hello"

$friend
[1] "Park"

$num
[1] 2

$alpha
[1] "z"

$word
[1] "hello"

$food
[1] "Pizza"  "Hotdog" "Rice"

## R Matrix

<br>

- 2차원 Vector를 표현하기 위한 방법. 행x열 구조.
- 마찬가지로 **index는 1부터 시작.**
- **matrix(행렬의 구성원소, nrow = 행의 갯수, ncol = 열의 갯수, dimnames = 행/열의 이름)** 를 통해 생성.
    - 데이터는 **열 중심**으로 들어감.
        - 1행 1열, 2행 1열, 1행 2열, 2행 2열 순으로.
    - **행 중심으로 기록**하고자 한다면?
        - 끝 인자에 **byrow = True** 를 추가해주면 됨.
- 동일한 길이의 Vector를 여러개 쌓은 셈.
- 각 행,열 요소의 **데이터 형식은 같아야 함.** 숫자면 숫자만, 문자면 문자만.


In [12]:
# 2행 3열의 Matrix 생성
# 6개의 데이터에 대해 2행 지정. 열은 당연히 3열. 생략가능.
age <- matrix(c(25, 33, 32, 37, 27, 38), nrow = 2)
age # 열 중심으로 데이터가 들어감을 확인할 수 있음.
# 각 위치는 열 : [,1] [,2] [,3] // 행 : [1,] [2,]

# 행 중심으로?
age2 <- matrix(c(25, 33, 32, 37, 27, 38), ncol = 3, byrow = TRUE)
age2

[,1] [,2] [,3]
[1,] 25   32   27  
[2,] 33   37   38

[,1] [,2] [,3]
[1,] 25   33   32  
[2,] 37   27   38

**행/열 이름 지정**

<br>

- **dimnames(행렬) <- 값** 을 통해 이름 지정이 가능.
- **행 중심으로 행렬 선언시 (이름)값도 행 우선으로 들어감.**

In [15]:
info <- matrix(c(177, 68, 165, 57, 160, 55, 175, 60), nrow = 4, byrow = TRUE)
info

# 행 중심이므로 이름도 행 우선으로 들어감.
dimnames(info) <- list(c('1번', '2번', '3번', '4번'), c('키(cm)', '몸무게(kg)'))
info

[,1] [,2]
[1,] 177  68  
[2,] 165  57  
[3,] 160  55  
[4,] 175  60

키(cm) 몸무게(kg)
1번 177    68        
2번 165    57        
3번 160    55        
4번 175    60

**행/열에 새로운 행/열 추가**

<br>

- 행 추가 : **rbind(행렬, 행에 추가할 원소)**
- 열 추가 : **cbind(행렬, 열에 추가할 원소)**

<br>

- 연산 시에만 적용되는 연산.
- 원본 행렬엔 영향 X. 
    - 원본을 바꾸려면 **<- 연산자** 써서 넣으면 됨.

In [19]:
info

# 행 추가
a1 <- c(167, 54)
a2 <- c(178, 70)
rbind(info, a1, a2)

# 열 추가
cbind(info, c('남', '여', '여', '남'))

키(cm) 몸무게(kg)
1번 177    68        
2번 165    57        
3번 160    55        
4번 175    60

키(cm) 몸무게(kg)
1번 177    68        
2번 165    57        
3번 160    55        
4번 175    60        
a1  167    54        
a2  178    70

키(cm) 몸무게(kg)   
1번 177    68         남
2번 165    57         여
3번 160    55         여
4번 175    60         남